name: dodo_pizza
description: A clone of Dodo Pizza app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.3
  country_flags:
    path: packages/country_flags
  dodo_icons:
    path: packages/dodo_icons
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true

  assets:
    - assets/countries/
    - assets/images/
    - assets/menu/

flutter_intl:
  enabled: true
  arb_dir: lib/localization/src/l10n
  output_dir: lib/localization/src/generated

flutter_native_splash:
  color: "#ff6900"
  image: assets/splash/splash_image.png

  android_12:
    color: "#ff6900"
    image: assets/splash/splash_image_android_12.png